version: 2
updates:
- package-ecosystem: composer
  directory: "/app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/http-kernel
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.2.0
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
