version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - 9000:9000
    volumes:
      - ./php/app:/var/www/html
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 33060:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
