version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
    ports:
      - 8888:80
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  app:
    container_name: app
    build:
      context: ./app
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 33060:3306
    volumes:
      - ./config/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
